blank_issues_enabled: true
contact_links:
  - name: Add new ToDo
    about: made by config.yml
    # edit {username} and {repo} for your environment
    url: https://github.com/nawaday-code/nightwork/issues/new?template=custom.md&projects=nawaday-code%2Fnightwork%2F1&labels=ToDo
